---
galaxy_info:
  role_name: hestia
  namespace: accelior
  author: jmvl
  description: HestiaCP service maintenance role with Dovecot, Exim4, and monitoring
  company: Accelior
  license: MIT
  min_ansible_version: "2.15"

  platforms:
    - name: Debian
      versions:
        - bookworm  # Debian 12
        - bullseye  # Debian 11

  galaxy_tags:
    - mail
    - email
    - hestiacp
    - dovecot
    - exim
    - maintenance
    - monitoring

dependencies: []
